name       : haskell-Diff
version    : 0.4.0
release    : 2
source     :
    - https://hackage.haskell.org/package/Diff-0.4.0/Diff-0.4.0.tar.gz : 7290ac098ad8b4748b9c10e494cc85ba54af688226ae69a465aa7b4c73f149c7
license    : BSD-3-Clause
component  : programming.haskell
summary    : Implementation of the standard diff algorithm, and utilities for pretty printing
description: |
    Implementation of the standard diff algorithm, and utilities for pretty printing.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
